apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: xmrt5ovow-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-01932c0cb8.ezm0.p3.openshiftapps.com/rhtap/rhtap-qe:a921d757adf974dbea41170b8475a8df51ce0687@sha256:d29f95a6d182d6e2ea5e3a40cd34ed76353d5c8036b75d8a85c20f847381745b
        name: container-image  
